# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bira"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git gitfast heroku vi-mode)
export PATH=$HOME/Projects/dotfiles/bin:$PATH
export PATH=/usr/local/bin:${PATH/\/usr\/local\/bin:/}
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="/usr/local/exercism:$PATH"
export EDITOR='vim'
#export CC=/usr/bin/llvm-gcc-4.2

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
 if [[ -a ~/.localrc ]]
 then
   source ~/.localrc
 fi

# Don't auto title (works for tmux)
DISABLE_AUTO_TITLE=true
source $ZSH/oh-my-zsh.sh

# Customize to your needs...
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

[[ -s "$HOME/.nvm/nvm.sh" ]] && . "$HOME/.nvm/nvm.sh" # This loads NVM

# Tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# Fix ZSH git completion
zstyle ':completion:*:*:git:*' script /usr/local/etc/bash_completion.d/git-completion.bash

# Aliases
alias byword='open -a /Applications/Byword.app/Contents/MacOS/Byword'

# Desk-flow aliases
alias dfst="bundle exec desk-flow ticket start"
alias dfs="bundle exec desk-flow ticket submit"
alias dfc="bundle exec desk-flow ticket complete"
alias dfr="bundle exec desk-flow ticket review"
alias dfu="bundle exec desk-flow ticket update"

export PROMPT="╭─${user_host} ${current_dir} ${rvm_ruby} ${git_branch}╰─%B$%b "

bindkey '^R' history-incremental-search-backward

function define_vim_wrappers()
{
  vim_commands=(
    eview evim gview gvim gvimdiff gvimtutor rgview
    rgvim rview rvim vim vimdiff vimtutor xxd mvim
  )

  for cmd in ${vim_commands[@]}; do
    cmd_path=`/usr/bin/env which -a "${cmd}" 2>/dev/null | grep '^/'`
    if [ -x "${cmd_path}" ]; then
      eval "function ${cmd} () { (unset GEM_HOME; unset GEM_PATH; $cmd_path \$@) }"
    fi
  done
}
define_vim_wrappers

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

cd ..;1
