. ~/Projects/dotfiles/bash/env
. ~/Projects/dotfiles/bash/config
. ~/Projects/dotfiles/bash/aliases
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export CC=gcc-4.2
#[ -f ~/.bundler-exec.sh ] && source ~/.bundler-exec.sh

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
